# Adding this because Tailwind CSS classes can be long
Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

# Leaving this for next version of rubocop.yml
Gemspec/RequiredRubyVersion:
  Enabled: false

Style/Documentation:
  Enabled: false
