// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import controllers from './**/*_controller.js';

// import '../../../../../app/ui/components/rails_ui/index.js'


controllers.forEach((controller) => {
  application.register(controller.name, controller.module.default);
});


import uiControllers from "../../../../../app/ui/components/rails_ui/**/*index.js"


console.log(uiControllers)

uiControllers.forEach((controller) => {
  if(controller.module.default){
    // ..--..--..--..--..--app--ui--components--rails-ui--skeleton
    let name = controller.name.replace("--index.js", "")
    name = name.replace("..--..--..--..--..--app--ui--components--rails-ui--", "")
    name = `ui-${name}`
    console.log("ADDINDG CONTROLLER", name)
    application.register(name, controller.module.default);
  }

});

console.log(application)








